#!/usr/bin/env python3
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]


def strip_final_return(source: str, return_name: str) -> str:
    lines = source.rstrip().splitlines()
    while lines and not lines[-1].strip():
        lines.pop()
    if lines and lines[-1].strip() == f'return {return_name}':
        lines.pop()
    return '\n'.join(lines).rstrip() + '\n'


def build_game(game_name: str) -> Path:
    game_dir = ROOT / 'src' / 'games' / game_name
    ui_path = ROOT / 'src' / 'ui' / 'VantageUILibrary.lua'
    logic_path = game_dir / 'GameLogic.lua'
    game_ui_path = game_dir / 'GameUI.lua'
    final_path = game_dir / 'Final_Injectable.lua'

    missing = [p for p in [ui_path, logic_path, game_ui_path] if not p.exists()]
    if missing:
        raise SystemExit('Missing source files:\n' + '\n'.join(str(p.relative_to(ROOT)) for p in missing))

    ui = strip_final_return(ui_path.read_text(encoding='utf-8'), 'Library')
    logic = strip_final_return(logic_path.read_text(encoding='utf-8'), 'Logic')
    game_ui = strip_final_return(game_ui_path.read_text(encoding='utf-8'), 'BuildUI')

    output = f"""-- [[ VANTAGE HUB: {game_name} - GENERATED SINGLE FILE ]]
-- Generated from:
-- - src/ui/VantageUILibrary.lua
-- - src/games/{game_name}/GameLogic.lua
-- - src/games/{game_name}/GameUI.lua
-- Runner note: this file is self-contained. Paste/run this file only; no external Library.lua, Roact, or module require is needed.
-- Do not edit this file directly unless doing an emergency patch. Edit source files and rerun scripts/build_game.py.

-- =============================================================================
-- [ EMBEDDED UI LIBRARY ]
-- =============================================================================
{ui}
-- =============================================================================
-- [ EMBEDDED GAME LOGIC ]
-- =============================================================================
{logic}
-- =============================================================================
-- [ MAIN: UI EXECUTION ]
-- =============================================================================
{game_ui}
BuildUI(Library, Logic)

print("Vantage Hub {game_name} Loaded Successfully!")
"""
    final_path.write_text(output, encoding='utf-8')
    return final_path


def main() -> None:
    game_name = sys.argv[1] if len(sys.argv) > 1 else 'SurviveTheApocalypse'
    final_path = build_game(game_name)
    print(f'Built {final_path.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
